# Generated by Django 5.1.2 on 2024-10-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reporting',
            field=models.CharField(max_length=255),
        ),
    ]
