# Generated by Django 5.1.2 on 2024-10-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_cart_cartitem_order'),
        ('catalogue', '0005_remove_review_updated_at_alter_review_created_at'),
    ]

    operations = [
    ]
