# Generated by Django 5.1.3 on 2024-12-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_likereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likeReview_count',
            field=models.IntegerField(default=0),
        ),
    ]
