# Generated by Django 5.1.2 on 2024-10-27 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 11, 8, 54, 581394)),
        ),
    ]
