# Generated by Django 5.1.2 on 2024-10-26 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 3, 59, 11, 840891)),
        ),
    ]
